## Import Necessary Libraries

In [1]:
!pip install ktrain

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.3/25.3 MB 13.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 45.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 263.7/263.7 kB 21.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 17.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.8/468.8 kB 33.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... - done
  Preparing metadata (setup.py) ... - done
  Preparing metadata (setup.py) ... - done
  Preparing metadata (setup.py) ... - done
  Preparing metadata (setup.py) ... - done
  Preparing metadata (setup.py) ... - done
  Preparing metadata (setup.py) ... - done
  Created wheel for ktrain: filename=ktrain-0.31.10-py3-none-any.whl size=25312982 sha256=2199028482af9e09fab45b07b630cbfe6f3ec9da186b24f0ef227bb2b

In [2]:
import os
import ktrain

In [3]:
%%time
for dirname, _, filenames in os.walk('/kaggle/input'):
    #for filename in filenames:
    #print(os.path.join(dirname, filenames))
    print(dirname)

/kaggle/input
/kaggle/input/imdb-review
/kaggle/input/imdb-review/aclImdb
/kaggle/input/imdb-review/aclImdb/test
/kaggle/input/imdb-review/aclImdb/test/pos
/kaggle/input/imdb-review/aclImdb/test/neg
/kaggle/input/imdb-review/aclImdb/train
/kaggle/input/imdb-review/aclImdb/train/pos
/kaggle/input/imdb-review/aclImdb/train/neg
/kaggle/input/imdb-review/aclImdb/train/unsup
CPU times: user 469 ms, sys: 1.17 s, total: 1.64 s
Wall time: 2min 12s


## Preprocessing
The texts_from_folder function will load the training and validation data from the specified folder and automatically preprocess it according to BERT's requirements. In doing so, the BERT model and vocabulary will be automatically downloaded.

In [4]:
%%time
IMDB_DATADIR ="/kaggle/input/imdb-review/aclImdb"
(x_train, y_train), (x_test, y_test), preproc = ktrain.text.texts_from_folder(IMDB_DATADIR, 
                                                                              maxlen=500, 
                                                                              preprocess_mode='bert',
                                                                              train_test_names=['train', 'test'],
                                                                              classes=['pos', 'neg'])

detected encoding: utf-8
downloading pretrained BERT model (uncased_L-12_H-768_A-12.zip)...
[██████████████████████████████████████████████████]
extracting pretrained BERT model...
done.

cleanup downloaded zip...
done.

preprocessing train...
language: en


Is Multi-Label? False
preprocessing test...
language: en


CPU times: user 2min 46s, sys: 5.65 s, total: 2min 51s
Wall time: 8min


In [5]:
print('BERT Model')
print('Classes >>>',preproc.get_classes())
print('Tokenizer >>>',preproc.get_tokenizer())
print('Max Length >>>',preproc.maxlen)
print('Max Features >>>',preproc.max_features)
#print('Token Dictionary >>>',preproc.tok_dct)

BERT Model
Classes >>> ['neg', 'pos']
Tokenizer >>> <keras_bert.tokenizer.Tokenizer object at 0x7f59492b4690>
Max Length >>> 500
Max Features >>> 20000


In [6]:
print('*'*20)
print('Training Data :',len(x_train))
print('\nTraining Label Shape:',y_train.shape,'\n',y_train)
print('\nTraining Input, Shape :',x_train[0].shape,'\n',x_train[0])
print('\nTraining Mask, Shape :',x_train[1].shape,'\n',x_train[1])

print('*'*20)
print('Testing Data :',len(x_train))
print('\nTesting Label Shape:',y_train.shape,'\n',y_train)
print('\nTesting Input, Shape :',x_train[0].shape,'\n',x_train[0])
print('\nTesting Mask, Shape :',x_train[1].shape,'\n',x_train[1])

********************
Training Data : 2

Training Label Shape: (25000, 2) 
 [[0. 1.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]

Training Input, Shape : (25000, 500) 
 [[ 101 5717 2154 ...    0    0    0]
 [ 101 2616 2064 ...    0    0    0]
 [ 101 3071 3248 ...    0    0    0]
 ...
 [ 101 3083 3427 ...    0    0    0]
 [ 101 1045 3422 ...    0    0    0]
 [ 101 7078 1996 ...    0    0    0]]

Training Mask, Shape : (25000, 500) 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
********************
Testing Data : 2

Testing Label Shape: (25000, 2) 
 [[0. 1.]
 [1. 0.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]

Testing Input, Shape : (25000, 500) 
 [[ 101 5717 2154 ...    0    0    0]
 [ 101 2616 2064 ...    0    0    0]
 [ 101 3071 3248 ...    0    0    0]
 ...
 [ 101 3083 3427 ...    0    0    0]
 [ 101 1045 3422 ...    0    0    0]
 [ 101 7078 1996 ...    0    0    0]]

Testing Mask, Shape : (25000, 500) 
 

## Loading a pre trained BERT and wrapping it in a ktrain.learner object

In [7]:
model = ktrain.text.text_classifier('bert', (x_train, y_train), preproc=preproc)
learner = ktrain.get_learner(model,train_data=(x_train, y_train), val_data=(x_test, y_test), batch_size=6)

Is Multi-Label? False
maxlen is 500
done.


## Training and Tuning the model's parameters

In [8]:
learner.fit_onecycle(lr =2e-5, epochs = 1)



begin training using onecycle policy with max lr of 2e-05...
4167/4167 [==============================] - 2664s 635ms/step - loss: 0.2494 - accuracy: 0.8986 - val_loss: 0.1703 - val_accuracy: 0.9354


#### Reference
[BERT Text Classification in 3 Lines of Code Using Keras](https://towardsdatascience.com/bert-text-classification-in-3-lines-of-code-using-keras-264db7e7a358)